@startuml OAuth2

!$ICONURL = "https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v3.0.0/icons"
!include $ICONURL/common.puml
!include $ICONURL/devicons2/nestjs_original.puml
!include $ICONURL/devicons2/oauth.puml
!include $ICONURL/font-awesome/user.puml
!include $ICONURL/devicons/redis.puml

skinparam defaultTextAlignment center
skinparam participantFontAlignment center

FA_USER(Client, "Client", participant, SkyBlue) #White
DEV2_NESTJS_ORIGINAL(Backend, "Backend", participant, #E0234E) #White
DEV_REDIS(Redis, "Redis", participant, #D82C20) #White
DEV2_OAUTH(OAuth, "OAuth", participant, #4285F4) #White

Client -> Backend: [A-01] 구글 로그인 페이지 요청
Backend -> Client: [A-01] 구글 로그인 페이지 리다이렉션
Client -> OAuth: 로그인 및 개인정보 수집 동의
OAuth -> Client: [A-02] Authorization code를 포함한 승인된 리다이렉션 URI로 사용자를 리다이렉션
Client -> Backend: [A-02] Authorization code 전달 및 서비스 요청
Backend -> OAuth: [A-02] 사용자 정보 요청
OAuth -> Backend: [A-02] 사용자 정보 제공
Backend -> Backend: [A-02] 회원가입 처리 및 JWT 토큰 발급을 위한 일회용 Grant code 생성
Backend -> Redis: [A-02] 유효 기간을 짧게 설정하여 Grant code 저장
Backend -> Client: [A-02] 서비스 특정 페이지 리다이렉션 및 URL 쿼리 파라미터로 Grant code 전달
Client -> Client: URL에서 Grant code 추출
Client -> Backend: [A-03] Grant code를 전달하며 JWT 토큰 요청
Backend -> Redis: [A-03] Grant code 요청
Redis -> Backend: [A-03] Grant code 제공
Backend -> Backend: [A-03] Grant code 검증 및 JWT 액세스 토큰, 리프레시 토큰 생성
Backend -> Redis: [A-03] 리프레시 토큰 저장
Backend -> Client: [A-03] 액세스 토큰, 리프레시 토큰 제공
Client -> Client: 스토리지에 토큰 저장

@enduml
