@startuml Microservices

!$ICONURL = "https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v3.0.0/icons"
!include $ICONURL/common.puml
!include $ICONURL/devicons2/nestjs_original.puml
!include $ICONURL/devicons2/fastapi.puml
!include $ICONURL/devicons2/rabbitmq_original.puml
!include $ICONURL/font-awesome/user.puml
!include $ICONURL/devicons/redis.puml
!include $ICONURL/font-awesome/user.puml

left to right direction
skinparam defaultTextAlignment center

FA_USER(User, "User", rectangle, SkyBlue) #White
DEV2_NESTJS_ORIGINAL(MainService1, "Main Service", node, #E0234E) #White
DEV2_NESTJS_ORIGINAL(MainService2, "Main Service", node, #E0234E) #White
DEV2_NESTJS_ORIGINAL(MainService3, "Main Service", node, #E0234E) #White
DEV_REDIS(Redis, "Redis", queue, #D82C20) #White

User --> MainService1
User --> MainService2
User --> MainService3
User <-- MainService1
User <-- MainService2
User <-- MainService3

MainService1 --> Redis
MainService2 --> Redis
MainService3 --> Redis
MainService1 <-- Redis
MainService2 <-- Redis
MainService3 <-- Redis

@enduml
